"use client"

import { createContext, useContext, useState, type ReactNode } from "react"

type Language = "en" | "hi"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
  translateCategory: (category: string) => string
  translateEvent: (eventId: string, field: 'title' | 'description', defaultValue: string) => string
  translateOrganizer: (organizerName: string) => string
  translateLocation: (location: string) => string
}

const translations = {
  en: {
    "hero.title": "Discover Amazing Arts & Cultural Events",
    "hero.subtitle": "Unite Through Arts - Find Jatra, Cinema, Music, Dance & More",
    "stats.eventsBooked": "Events Booked",
    "stats.artists": "Registered Artists",
    "stats.tickets": "Tickets Sold",
    "stats.learners": "Active Learners",
    "stats.orders": "Custom Orders",
    "featured.title": "Featured Events",
    "featured.subtitle": "Handpicked arts and cultural experiences",
    "footer.discover": "Discover",
    "footer.browse": "Browse Events",
    "footer.trending": "Trending",
    "footer.category": "By Category",
    "footer.artists": "Artists",
    "footer.register": "Register as Artist",
    "footer.monetize": "Monetize Your Art",
    "footer.resources": "Resources",
    "footer.support": "Support",
    "footer.legal": "Legal",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.refund": "Refund Policy",
    "explore": "Explore Events",
    "search.eventType": "Event Type",
    "search.eventPlaceholder": "Music, Jatra, Cinema...",
    "search.location": "Location",
    "search.locationPlaceholder": "City or ZIP code",
    "search.date": "Date",
    "search.button": "Search",
    "category.discover": "Discover",
    "category.eventsNow": "events happening now",
    "category.viewAll": "View All",
    "card.featured": "Featured",
    "card.free": "Free",
    "card.attending": "attending",
    "card.online": "Online",
    "card.view": "View",
    "filters.title": "Filters",
    "filters.clearAll": "Clear All",
    "filters.category": "Category",
    "filters.location": "Location",
    "filters.locationPlaceholder": "City or ZIP",
    "filters.priceRange": "Price Range",
    "filters.min": "Min",
    "filters.max": "Max",
    "filters.eventType": "Event Type",
    "filters.allTypes": "All Types",
    "filters.corporate": "Corporate event",
    "filters.social": "Social events",
    "filters.entertainment": "Entertainment & public events",
    "filters.education": "Education e-learning & Youth events",
    "filters.charity": "Charity & community events",
    "filters.virtual": "Virtual event",
    "filters.casting": "Casting Audition",
    "grid.noEvents": "No events found. Try adjusting your filters.",
    "grid.loading": "Loading more events...",
    "newsletter.title": "Stay Updated",
    "newsletter.subtitle": "Get the latest events delivered to your inbox. Never miss out on amazing experiences.",
    "newsletter.placeholder": "Enter your email",
    "newsletter.subscribe": "Subscribe",
    "newsletter.subscribed": "Subscribed!",
    "inquiry.title": "Inquiry Form",
    "inquiry.subtitle": "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    "inquiry.firstNamePlaceholder": "First Name",
    "inquiry.lastNamePlaceholder": "Last Name",
    "inquiry.phonePlaceholder": "Phone Number",
    "inquiry.emailPlaceholder": "Email Address",
    "inquiry.cityPlaceholder": "City",
    "inquiry.messagePlaceholder": "Your Message",
    "inquiry.submit": "Send Message",
    "inquiry.success": "Thank You!",
    "inquiry.successMessage": "Your inquiry has been submitted successfully. We'll get back to you soon.",
    "terms.title": "Terms of Service",
    "terms.subtitle": "Please read these terms carefully",
    "terms.updated": "Last updated: December 2024",
    "terms.section1": "1. Acceptance of Terms",
    "terms.section1.text": "By accessing and using MOOKALAA, you accept and agree to be bound by the terms and provision of this agreement.",
    "terms.section2": "2. Description of Service",
    "terms.section2.text": "MOOKALAA is a platform that connects users with arts and cultural events including Jatra, Cinema, Music, Dance, Festivals, Workshops, and Custom Orders from artists worldwide.",
    "terms.section3": "3. User Accounts",
    "terms.section3.text": "To access certain features, you must create an account. You are responsible for:",
    "terms.section4": "4. Booking and Payments",
    "terms.section4.text": "When you book an event through MOOKALAA:",
    "terms.section5": "5. User Conduct",
    "terms.section5.text": "You agree not to:",
    "terms.section6": "6. Event Organizers",
    "terms.section6.text": "Event organizers using MOOKALAA agree to:",
    "terms.section7": "7. Intellectual Property",
    "terms.section7.text": "The MOOKALAA platform, including its content, features, and functionality, is owned by MOOKALAA and is protected by copyright, trademark, and other intellectual property laws.",
    "terms.section8": "8. Disclaimers",
    "terms.section8.text": "MOOKALAA provides the platform 'as is' without warranties of any kind. We do not guarantee the accuracy, completeness, or reliability of any content or services.",
    "terms.section9": "9. Limitation of Liability",
    "terms.section9.text": "MOOKALAA shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service.",
    "terms.section10": "10. Termination",
    "terms.section10.text": "We may terminate or suspend your account and access to the service at our sole discretion, without prior notice, for conduct that we believe violates these Terms.",
    "terms.section11": "11. Changes to Terms",
    "terms.section11.text": "We reserve the right to modify these terms at any time. We will notify users of any material changes via email or through the platform.",
    "terms.section12": "12. Contact Information",
    "terms.section12.text": "If you have any questions about these Terms of Service, please contact us at:",
    "terms.bullet3.1": "Maintaining the confidentiality of your account credentials",
    "terms.bullet3.2": "All activities that occur under your account",
    "terms.bullet3.3": "Providing accurate and complete information",
    "terms.bullet3.4": "Updating your information as necessary",
    "terms.bullet4.1": "You agree to pay all applicable fees",
    "terms.bullet4.2": "Payments are processed securely through third-party providers",
    "terms.bullet4.3": "Booking confirmations are subject to event organizer approval",
    "terms.bullet4.4": "Cancellation policies vary by event and organizer",
    "terms.bullet5.1": "Use the service for any unlawful purpose",
    "terms.bullet5.2": "Interfere with or disrupt the service",
    "terms.bullet5.3": "Upload harmful or malicious content",
    "terms.bullet5.4": "Violate any applicable laws or regulations",
    "terms.bullet5.5": "Infringe on intellectual property rights",
    "terms.bullet6.1": "Provide accurate event information",
    "terms.bullet6.2": "Honor confirmed bookings",
    "terms.bullet6.3": "Comply with applicable laws and regulations",
    "terms.bullet6.4": "Maintain appropriate insurance coverage",
    "privacy.title": "Privacy Policy",
    "privacy.subtitle": "Your privacy is important to us",
    "privacy.updated": "Last updated: December 2024",
    "privacy.section1": "1. Information We Collect",
    "privacy.section1.text": "At MOOKALAA, we collect information you provide directly to us, such as when you create an account, book events, or contact us for support.",
    "privacy.section2": "2. How We Use Your Information",
    "privacy.section2.text": "We use the information we collect to:",
    "privacy.section3": "3. Information Sharing",
    "privacy.section3.text1": "We do not sell, trade, or otherwise transfer your personal information to third parties without your consent, except as described in this policy.",
    "privacy.section3.text2": "We may share your information with:",
    "privacy.section4": "4. Data Security",
    "privacy.section4.text": "We implement appropriate security measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.",
    "privacy.section5": "5. Your Rights",
    "privacy.section5.text": "You have the right to:",
    "privacy.section6": "6. Cookies and Tracking",
    "privacy.section6.text": "We use cookies and similar technologies to enhance your experience, analyze usage, and provide personalized content.",
    "privacy.section7": "7. Contact Us",
    "privacy.section7.text": "If you have any questions about this Privacy Policy, please contact us at:",
    "privacy.bullet1.1": "Personal information (name, email, phone number)",
    "privacy.bullet1.2": "Payment information (processed securely through third-party providers)",
    "privacy.bullet1.3": "Event preferences and booking history",
    "privacy.bullet1.4": "Communication preferences",
    "privacy.bullet2.1": "Provide and improve our services",
    "privacy.bullet2.2": "Process bookings and payments",
    "privacy.bullet2.3": "Send you event recommendations and updates",
    "privacy.bullet2.4": "Provide customer support",
    "privacy.bullet2.5": "Comply with legal obligations",
    "privacy.bullet3.1": "Event organizers (only necessary booking details)",
    "privacy.bullet3.2": "Payment processors for transaction processing",
    "privacy.bullet3.3": "Service providers who assist in our operations",
    "privacy.bullet3.4": "Legal authorities when required by law",
    "privacy.bullet5.1": "Access your personal information",
    "privacy.bullet5.2": "Correct inaccurate information",
    "privacy.bullet5.3": "Delete your account and personal information",
    "privacy.bullet5.4": "Opt-out of marketing communications",
    "privacy.bullet5.5": "Data portability",
    "eventDetail.notFound": "Event Not Found",
    "eventDetail.backToEvents": "Back to Events",
    "eventDetail.date": "Date",
    "eventDetail.time": "Time",
    "eventDetail.location": "Location",
    "eventDetail.attending": "Attending",
    "eventDetail.addToCalendar": "Add to Calendar",
    "eventDetail.aboutOrganizer": "About the Organizer",
    "eventDetail.relatedEvents": "Related Events",
    "eventDetail.eventInfo": "Event Info",
    "eventDetail.entryFee": "Entry Fee",
    "eventDetail.eventType": "EVENT TYPE",
    "eventDetail.onlineEvent": "Online Event",
    "eventDetail.inPerson": "In-Person",
    "eventDetail.attendees": "ATTENDEES",
    "eventDetail.markInterested": "Mark as Interested",
    "eventDetail.shareEvent": "Share Event",
    "eventDetail.tags": "TAGS",
    "trending.title": "Trending Cities",
    "trending.subtitle": "Explore events in popular destinations",
    "trending.events": "events",
    "eventsPage.title": "Discover Events",
    "eventsPage.found": "Found",
    "eventsPage.events": "events",
    "eventsPage.gridView": "Grid View",
    "eventsPage.mapView": "Map View",
    "eventsPage.sortPopular": "Most Popular",
    "eventsPage.sortDate": "Nearest Date",
    "eventsPage.sortRecent": "Recently Added",
    "categories.Jatra": "Jatra",
    "categories.Cinema": "Cinema",
    "categories.Ollywood": "Ollywood",
    "categories.Jollywood": "Jollywood",
    "categories.Music": "Music",
    "categories.Influencer": "Influencer",
    "categories.Comedian": "Comedian",
    "categories.Sports": "Sports",
    "categories.YouTuber's": "YouTuber's",
    "categories.Dancer": "Dancer",
    "categories.Authors": "Authors",
    "categories.Poet": "Poet",
    "categories.Indian idol contestants": "Indian Idol Contestants",
    "categories.Theatre Artists": "Theatre Artists",
    "categories.Instrumentalist": "Instrumentalist",
    "categories.Magician": "Magician",
    "categories.RJ": "RJ",
    "event.2.title": "Jatra Theatre Festival",
    "event.2.description": "Immerse yourself in the vibrant world of Jatra - traditional folk theatre. Experience compelling narratives performed by master artists.",
    "event.33.title": "Cricket Championship Finals",
    "event.33.description": "Watch the thrilling finals of the city cricket championship live.",
    "event.34.title": "Marathon Run 2025",
    "event.34.description": "Participate in the annual city marathon and promote fitness and health.",
    "event.8.title": "Global Arts Summit - New York",
    "event.8.description": "Connect with international artists, curators, and culture enthusiasts. Showcase your work to a global audience.",
    "event.15.title": "Odissi Dance Festival",
    "event.15.description": "Experience the divine grace of Odissi dance with master performers showcasing classical choreography and contemporary interpretations.",
    "event.48.title": "Indian Idol Live Concert",
    "event.48.description": "Watch Indian Idol contestants perform live in this spectacular musical concert.",
    "event.22.title": "Ollywood Music Awards 2025",
    "event.22.description": "Annual awards ceremony celebrating the best of Odia film music and artists.",
    "event.1.title": "Odissi Dance Festival 2025",
    "event.1.description": "Celebrate the grace and elegance of Odissi dance with performances from acclaimed dancers. Experience traditional choreography and contemporary interpretations.",
    "event.35.title": "Football Tournament",
    "event.35.description": "Inter-city football tournament featuring top local teams.",
    "event.12.title": "Sitar Recital by Maestro",
    "event.12.description": "An evening of classical Hindustani music featuring maestro sitar player performing raags from morning to night traditions.",
    "event.14.title": "Photography Exhibition - Faces of India",
    "event.14.description": "A powerful photography exhibition showcasing portraits and stories of ordinary people from across India. Interactive artist talks.",
    "event.7.title": "Indian Classical Music Masterclass",
    "event.7.description": "Learn Indian classical music from Grammy-nominated musician. Cover raag theory, instrument techniques, and composition.",
    "event.18.title": "Indian Classical Music Concert",
    "event.18.description": "An enchanting evening of Indian classical music featuring renowned musicians performing traditional ragas and compositions.",
    "event.31.title": "Comedy Festival 2025",
    "event.31.description": "Three days of non-stop laughter with India's best comedians.",
    "event.37.title": "YouTube Creator Summit",
    "event.37.description": "Learn monetization strategies and growth hacks from successful YouTubers.",
    "event.3.title": "Learn Kathak Dance Online",
    "event.3.description": "Master the fundamentals of Kathak dance in this comprehensive online workshop. Learn from Kathak maestro with personalized feedback.",
    "event.10.title": "Digital Art & Animation Expo",
    "event.10.description": "Showcase digital artworks, animations, and interactive installations from emerging digital artists. Networking with tech & art professionals.",
    "event.17.title": "Traditional Jatra Folk Theatre",
    "event.17.description": "Experience authentic Bengali folk theatre with traditional Jatra performances featuring mythological stories and social themes.",
    "organizer.Odissi Classical Arts": "Odissi Classical Arts",
    "organizer.Global Jatra Collective": "Global Jatra Collective",
    "organizer.MOOKALAA Artists Network": "MOOKALAA Artists Network",
    "organizer.Dance India Movement": "Dance India Movement",
  },
  hi: {
    "hero.title": "अद्भुत कला और सांस्कृतिक कार्यक्रम खोजें",
    "hero.subtitle": "कला के माध्यम से एकजुट - जात्रा, सिनेमा, संगीत, नृत्य और अधिक खोजें",
    "stats.eventsBooked": "बुक किए गए कार्यक्रम",
    "stats.artists": "पंजीकृत कलाकार",
    "stats.tickets": "बेची गई टिकटें",
    "stats.learners": "सक्रिय शिक्षार्थी",
    "stats.orders": "कस्टम ऑर्डर",
    "featured.title": "विशेष कार्यक्रम",
    "featured.subtitle": "चुनिंदा कला और सांस्कृतिक अनुभव",
    "footer.discover": "खोजें",
    "footer.browse": "कार्यक्रम ब्राउज़ करें",
    "footer.trending": "ट्रेंडिंग",
    "footer.category": "श्रेणी के अनुसार",
    "footer.artists": "कलाकार",
    "footer.register": "कलाकार के रूप में पंजीकरण करें",
    "footer.monetize": "अपनी कला से कमाएं",
    "footer.resources": "संसाधन",
    "footer.support": "सहायता",
    "footer.legal": "कानूनी",
    "footer.privacy": "गोपनीयता",
    "footer.terms": "नियम",
    "footer.refund": "रिफंड नीति",
    "explore": "कार्यक्रम देखें",
    "search.eventType": "कार्यक्रम प्रकार",
    "search.eventPlaceholder": "संगीत, जात्रा, सिनेमा...",
    "search.location": "स्थान",
    "search.locationPlaceholder": "शहर या पिन कोड",
    "search.date": "तारीख",
    "search.button": "खोजें",
    "category.discover": "खोजें",
    "category.eventsNow": "कार्यक्रम अभी हो रहे हैं",
    "category.viewAll": "सभी देखें",
    "card.featured": "विशेष",
    "card.free": "मुफ्त",
    "card.attending": "उपस्थित",
    "card.online": "ऑनलाइन",
    "card.view": "देखें",
    "filters.title": "फ़िल्टर",
    "filters.clearAll": "सभी हटाएं",
    "filters.category": "श्रेणी",
    "filters.location": "स्थान",
    "filters.locationPlaceholder": "शहर या पिन कोड",
    "filters.priceRange": "मूल्य सीमा",
    "filters.min": "न्यूनतम",
    "filters.max": "अधिकतम",
    "filters.eventType": "कार्यक्रम प्रकार",
    "filters.allTypes": "सभी प्रकार",
    "filters.corporate": "कॉर्पोरेट कार्यक्रम",
    "filters.social": "सामाजिक कार्यक्रम",
    "filters.entertainment": "मनोरंजन और सार्वजनिक कार्यक्रम",
    "filters.education": "शिक्षा ई-लर्निंग और युवा कार्यक्रम",
    "filters.charity": "दान और सामुदायिक कार्यक्रम",
    "filters.virtual": "वर्चुअल कार्यक्रम",
    "filters.casting": "कास्टिंग ऑडिशन",
    "grid.noEvents": "कोई कार्यक्रम नहीं मिला। अपने फ़िल्टर समायोजित करने का प्रयास करें।",
    "grid.loading": "अधिक कार्यक्रम लोड हो रहे हैं...",
    "newsletter.title": "अपडेट रहें",
    "newsletter.subtitle": "अपने इनबॉक्स में नवीनतम कार्यक्रम प्राप्त करें। अद्भुत अनुभवों को कभी न चूकें।",
    "newsletter.placeholder": "अपना ईमेल दर्ज करें",
    "newsletter.subscribe": "सब्सक्राइब करें",
    "newsletter.subscribed": "सब्सक्राइब हो गया!",
    "inquiry.title": "पूछताछ फॉर्म",
    "inquiry.subtitle": "कोई प्रश्न है? हम आपसे सुनना पसंद करेंगे। हमें एक संदेश भेजें और हम जल्द से जल्द जवाब देंगे।",
    "inquiry.firstNamePlaceholder": "पहला नाम",
    "inquiry.lastNamePlaceholder": "अंतिम नाम",
    "inquiry.phonePlaceholder": "फोन नंबर",
    "inquiry.emailPlaceholder": "ईमेल पता",
    "inquiry.cityPlaceholder": "शहर",
    "inquiry.messagePlaceholder": "आपका संदेश",
    "inquiry.submit": "संदेश भेजें",
    "inquiry.success": "धन्यवाद!",
    "inquiry.successMessage": "आपकी पूछताछ सफलतापूर्वक जमा कर दी गई है। हम जल्द ही आपसे संपर्क करेंगे।",
    "terms.title": "सेवा की शर्तें",
    "terms.subtitle": "कृपया इन शर्तों को ध्यान से पढ़ें",
    "terms.updated": "अंतिम अपडेट: दिसंबर 2024",
    "terms.section1": "1. शर्तों की स्वीकृति",
    "terms.section1.text": "MOOKALAA तक पहुंचकर और उपयोग करके, आप इस समझौते की शर्तों और प्रावधानों से बंधे रहने के लिए स्वीकार करते हैं और सहमत होते हैं।",
    "terms.section2": "2. सेवा का विवरण",
    "terms.section2.text": "MOOKALAA एक मंच है जो उपयोगकर्ताओं को जात्रा, सिनेमा, संगीत, नृत्य, त्योहार, कार्यशालाओं और दुनिया भर के कलाकारों से कस्टम ऑर्डर सहित कला और सांस्कृतिक कार्यक्रमों से जोड़ता है।",
    "terms.section3": "3. उपयोगकर्ता खाते",
    "terms.section3.text": "कुछ सुविधाओं तक पहुंचने के लिए, आपको एक खाता बनाना होगा। आप निम्नलिखित के लिए जिम्मेदार हैं:",
    "terms.section4": "4. बुकिंग और भुगतान",
    "terms.section4.text": "जब आप MOOKALAA के माध्यम से कोई कार्यक्रम बुक करते हैं:",
    "terms.section5": "5. उपयोगकर्ता आचरण",
    "terms.section5.text": "आप सहमत हैं कि आप निम्नलिखित नहीं करेंगे:",
    "terms.section6": "6. कार्यक्रम आयोजक",
    "terms.section6.text": "MOOKALAA का उपयोग करने वाले कार्यक्रम आयोजक सहमत हैं:",
    "terms.section7": "7. बौद्धिक संपदा",
    "terms.section7.text": "MOOKALAA प्लेटफॉर्म, इसकी सामग्री, सुविधाओं और कार्यक्षमता का स्वामित्व MOOKALAA के पास है और यह कॉपीराइट, ट्रेडमार्क और अन्य बौद्धिक संपदा कानूनों द्वारा संरक्षित है।",
    "terms.section8": "8. अस्वीकरण",
    "terms.section8.text": "MOOKALAA प्लेटफॉर्म को 'जैसा है' किसी भी प्रकार की वारंटी के बिना प्रदान करता है। हम किसी भी सामग्री या सेवाओं की सटीकता, पूर्णता या विश्वसनीयता की गारंटी नहीं देते हैं।",
    "terms.section9": "9. दायित्व की सीमा",
    "terms.section9.text": "MOOKALAA आपकी सेवा के उपयोग से उत्पन्न किसी भी अप्रत्यक्ष, आकस्मिक, विशेष, परिणामी या दंडात्मक नुकसान के लिए उत्तरदायी नहीं होगा।",
    "terms.section10": "10. समाप्ति",
    "terms.section10.text": "हम अपने विवेक पर, बिना पूर्व सूचना के, आपके खाते और सेवा तक पहुंच को समाप्त या निलंबित कर सकते हैं, उस आचरण के लिए जो हमारे विचार में इन शर्तों का उल्लंघन करता है।",
    "terms.section11": "11. शर्तों में परिवर्तन",
    "terms.section11.text": "हम किसी भी समय इन शर्तों को संशोधित करने का अधिकार सुरक्षित रखते हैं। हम ईमेल या प्लेटफॉर्म के माध्यम से उपयोगकर्ताओं को किसी भी महत्वपूर्ण परिवर्तन की सूचना देंगे।",
    "terms.section12": "12. संपर्क जानकारी",
    "terms.section12.text": "यदि इन सेवा की शर्तों के बारे में आपके कोई प्रश्न हैं, तो कृपया हमसे संपर्क करें:",
    "terms.bullet3.1": "अपने खाते की प्रमाण पत्रों की गोपनीयता बनाए रखना",
    "terms.bullet3.2": "आपके खाते के तहत होने वाली सभी गतिविधियां",
    "terms.bullet3.3": "सटीक और पूर्ण जानकारी प्रदान करना",
    "terms.bullet3.4": "आवश्यकतानुसार अपनी जानकारी अपडेट करना",
    "terms.bullet4.1": "आप सभी लागू शुल्क का भुगतान करने के लिए सहमत हैं",
    "terms.bullet4.2": "भुगतान तीसरे पक्ष प्रदाताओं के माध्यम से सुरक्षित रूप से संसाधित किए जाते हैं",
    "terms.bullet4.3": "बुकिंग पुष्टिकरण कार्यक्रम आयोजक की स्वीकृति के अधीन है",
    "terms.bullet4.4": "रद्द करने की नीतियां कार्यक्रम और आयोजक के अनुसार भिन्न होती हैं",
    "terms.bullet5.1": "किसी भी गैरकानूनी उद्देश्य के लिए सेवा का उपयोग करना",
    "terms.bullet5.2": "सेवा में हस्तक्षेप करना या बाधित करना",
    "terms.bullet5.3": "हानिकारक या दुर्भावनापूर्ण सामग्री अपलोड करना",
    "terms.bullet5.4": "किसी भी लागू कानून या विनियमों का उल्लंघन करना",
    "terms.bullet5.5": "बौद्धिक संपदा अधिकारों का उल्लंघन करना",
    "terms.bullet6.1": "सटीक कार्यक्रम जानकारी प्रदान करना",
    "terms.bullet6.2": "पुष्टिकृत बुकिंग का सम्मान करना",
    "terms.bullet6.3": "लागू कानूनों और विनियमों का पालन करना",
    "terms.bullet6.4": "उचित बीमा कवरेज बनाए रखना",
    "privacy.title": "गोपनीयता नीति",
    "privacy.subtitle": "आपकी गोपनीयता हमारे लिए महत्वपूर्ण है",
    "privacy.updated": "अंतिम अपडेट: दिसंबर 2024",
    "privacy.section1": "1. हम कौन सी जानकारी एकत्र करते हैं",
    "privacy.section1.text": "MOOKALAA में, हम वह जानकारी एकत्र करते हैं जो आप सीधे हमें प्रदान करते हैं, जैसे कि जब आप खाता बनाते हैं, कार्यक्रम बुक करते हैं, या सहायता के लिए हमसे संपर्क करते हैं।",
    "privacy.section2": "2. हम आपकी जानकारी का उपयोग कैसे करते हैं",
    "privacy.section2.text": "हम एकत्रित जानकारी का उपयोग निम्नलिखित के लिए करते हैं:",
    "privacy.section3": "3. जानकारी साझा करना",
    "privacy.section3.text1": "हम आपकी सहमति के बिना आपकी व्यक्तिगत जानकारी को तीसरे पक्ष को नहीं बेचते, व्यापार नहीं करते या स्थानांतरित नहीं करते हैं, सिवाय इस नीति में वर्णित के अनुसार।",
    "privacy.section3.text2": "हम आपकी जानकारी निम्नलिखित के साथ साझा कर सकते हैं:",
    "privacy.section4": "4. डेटा सुरक्षा",
    "privacy.section4.text": "हम आपकी व्यक्तिगत जानकारी को अनधिकृत पहुंच, परिवर्तन, प्रकटीकरण या विनाश से बचाने के लिए उचित सुरक्षा उपाय लागू करते हैं।",
    "privacy.section5": "5. आपके अधिकार",
    "privacy.section5.text": "आपको निम्नलिखित अधिकार हैं:",
    "privacy.section6": "6. कुकीज़ और ट्रैकिंग",
    "privacy.section6.text": "हम आपके अनुभव को बढ़ाने, उपयोग का विश्लेषण करने और वैयक्तिकृत सामग्री प्रदान करने के लिए कुकीज़ और समान तकनीकों का उपयोग करते हैं।",
    "privacy.section7": "7. हमसे संपर्क करें",
    "privacy.section7.text": "यदि इस गोपनीयता नीति के बारे में आपके कोई प्रश्न हैं, तो कृपया हमसे संपर्क करें:",
    "privacy.bullet1.1": "व्यक्तिगत जानकारी (नाम, ईमेल, फोन नंबर)",
    "privacy.bullet1.2": "भुगतान जानकारी (तीसरे पक्ष प्रदाताओं के माध्यम से सुरक्षित रूप से संसाधित)",
    "privacy.bullet1.3": "कार्यक्रम पसंद और बुकिंग इतिहास",
    "privacy.bullet1.4": "संचार पसंद",
    "privacy.bullet2.1": "हमारी सेवाओं को प्रदान और सुधारना",
    "privacy.bullet2.2": "बुकिंग और भुगतान संसाधित करना",
    "privacy.bullet2.3": "आपको कार्यक्रम सिफारिशें और अपडेट भेजना",
    "privacy.bullet2.4": "ग्राहक सहायता प्रदान करना",
    "privacy.bullet2.5": "कानूनी दायित्वों का पालन करना",
    "privacy.bullet3.1": "कार्यक्रम आयोजक (केवल आवश्यक बुकिंग विवरण)",
    "privacy.bullet3.2": "लेनदेन प्रसंस्करण के लिए भुगतान प्रोसेसर",
    "privacy.bullet3.3": "सेवा प्रदाता जो हमारे संचालन में सहायता करते हैं",
    "privacy.bullet3.4": "कानून द्वारा आवश्यक होने पर कानूनी अधिकारी",
    "privacy.bullet5.1": "अपनी व्यक्तिगत जानकारी तक पहुंचें",
    "privacy.bullet5.2": "गलत जानकारी को सही करें",
    "privacy.bullet5.3": "अपना खाता और व्यक्तिगत जानकारी हटाएं",
    "privacy.bullet5.4": "मार्केटिंग संचार से ऑप्ट-आउट करें",
    "privacy.bullet5.5": "डेटा पोर्टेबिलिटी",
    "eventDetail.notFound": "कार्यक्रम नहीं मिला",
    "eventDetail.backToEvents": "कार्यक्रमों पर वापस जाएं",
    "eventDetail.date": "तारीख",
    "eventDetail.time": "समय",
    "eventDetail.location": "स्थान",
    "eventDetail.attending": "उपस्थित",
    "eventDetail.addToCalendar": "कैलेंडर में जोड़ें",
    "eventDetail.aboutOrganizer": "आयोजक के बारे में",
    "eventDetail.relatedEvents": "संबंधित कार्यक्रम",
    "eventDetail.eventInfo": "कार्यक्रम जानकारी",
    "eventDetail.entryFee": "प्रवेश शुल्क",
    "eventDetail.eventType": "कार्यक्रम प्रकार",
    "eventDetail.onlineEvent": "ऑनलाइन कार्यक्रम",
    "eventDetail.inPerson": "व्यक्तिगत रूप से",
    "eventDetail.attendees": "उपस्थित लोग",
    "eventDetail.markInterested": "रुचि के रूप में चिह्नित करें",
    "eventDetail.shareEvent": "कार्यक्रम साझा करें",
    "eventDetail.tags": "टैग",
    "trending.title": "ट्रेंडिंग शहर",
    "trending.subtitle": "लोकप्रिय गंतव्यों में कार्यक्रमों का अन्वेषण करें",
    "trending.events": "कार्यक्रम",
    "eventsPage.title": "कार्यक्रम खोजें",
    "eventsPage.found": "मिले",
    "eventsPage.events": "कार्यक्रम",
    "eventsPage.gridView": "ग्रिड व्यू",
    "eventsPage.mapView": "मैप व्यू",
    "eventsPage.sortPopular": "सबसे लोकप्रिय",
    "eventsPage.sortDate": "निकटतम तारीख",
    "eventsPage.sortRecent": "हाल ही में जोड़े गए",
    "categories.Jatra": "जात्रा",
    "categories.Cinema": "सिनेमा",
    "categories.Ollywood": "ओलीवुड",
    "categories.Jollywood": "जॉलीवुड",
    "categories.Music": "संगीत",
    "categories.Influencer": "प्रभावक",
    "categories.Comedian": "कॉमेडियन",
    "categories.Sports": "खेल",
    "categories.YouTuber's": "यूट्यूबर",
    "categories.Dancer": "नर्तक",
    "categories.Authors": "लेखक",
    "categories.Poet": "कवि",
    "categories.Indian idol contestants": "इंडियन आइडल प्रतियोगी",
    "categories.Theatre Artists": "रंगमंच कलाकार",
    "categories.Instrumentalist": "वाद्ययंत्र वादक",
    "categories.Magician": "जादूगर",
    "categories.RJ": "आरजे",
    "event.2.title": "जात्रा थिएटर फेस्टिवल",
    "event.2.description": "जात्रा की जीवंत दुनिया में डूब जाएं - पारंपरिक लोक रंगमंच। मास्टर कलाकारों द्वारा प्रस्तुत सम्मोहक कथाओं का अनुभव करें।",
    "event.33.title": "क्रिकेट चैंपियनशिप फाइनल",
    "event.33.description": "शहर की क्रिकेट चैंपियनशिप के रोमांचक फाइनल को लाइव देखें।",
    "event.34.title": "मैराथन रन 2025",
    "event.34.description": "वार्षिक शहर मैराथन में भाग लें और फिटनेस और स्वास्थ्य को बढ़ावा दें।",
    "event.8.title": "ग्लोबल आर्ट्स समिट - न्यूयॉर्क",
    "event.8.description": "अंतर्राष्ट्रीय कलाकारों, क्यूरेटरों और संस्कृति प्रेमियों से जुड़ें। अपने काम को वैश्विक दर्शकों के सामने प्रदर्शित करें।",
    "event.15.title": "ओडिसी नृत्य महोत्सव",
    "event.15.description": "शास्त्रीय नृत्यकला और समकालीन व्याख्याओं को प्रदर्शित करने वाले मास्टर कलाकारों के साथ ओडिसी नृत्य की दिव्य कृपा का अनुभव करें।",
    "event.48.title": "इंडियन आइडल लाइव कॉन्सर्ट",
    "event.48.description": "इस शानदार संगीत कॉन्सर्ट में इंडियन आइडल प्रतियोगियों को लाइव प्रदर्शन करते देखें।",
    "event.22.title": "ओलीवुड संगीत पुरस्कार 2025",
    "event.22.description": "ओड़िया फिल्म संगीत और कलाकारों के सर्वश्रेष्ठ का जश्न मनाने वाला वार्षिक पुरस्कार समारोह।",
    "event.1.title": "ओडिसी नृत्य महोत्सव 2025",
    "event.1.description": "प्रशंसित नर्तकों के प्रदर्शन के साथ ओडिसी नृत्य की कृपा और सुंदरता का जश्न मनाएं। पारंपरिक नृत्यकला और समकालीन व्याख्याओं का अनुभव करें।",
    "event.35.title": "फुटबॉल टूर्नामेंट",
    "event.35.description": "शीर्ष स्थानीय टीमों की विशेषता वाला अंतर-शहर फुटबॉल टूर्नामेंट।",
    "event.12.title": "मास्टरो द्वारा सितार वादन",
    "event.12.description": "शास्त्रीय हिंदुस्तानी संगीत की एक शाम जिसमें मास्टरो सितार वादक सुबह से रात की परंपराओं से राग प्रस्तुत करते हैं।",
    "event.14.title": "फोटोग्राफी प्रदर्शनी - भारत के चेहरे",
    "event.14.description": "पूरे भारत से आम लोगों के चित्र और कहानियों को प्रदर्शित करने वाली एक शक्तिशाली फोटोग्राफी प्रदर्शनी। इंटरैक्टिव कलाकार वार्ता।",
    "event.7.title": "भारतीय शास्त्रीय संगीत मास्टरक्लास",
    "event.7.description": "ग्रैमी-नामांकित संगीतकार से भारतीय शास्त्रीय संगीत सीखें। राग सिद्धांत, वाद्ययंत्र तकनीक और रचना को कवर करें।",
    "event.18.title": "भारतीय शास्त्रीय संगीत कॉन्सर्ट",
    "event.18.description": "प्रसिद्ध संगीतकारों द्वारा पारंपरिक राग और रचनाओं का प्रदर्शन करते हुए भारतीय शास्त्रीय संगीत की एक मनमोहक शाम।",
    "event.31.title": "कॉमेडी फेस्टिवल 2025",
    "event.31.description": "भारत के सर्वश्रेष्ठ कॉमेडियनों के साथ तीन दिन की नॉन-स्टॉप हंसी।",
    "event.37.title": "यूट्यूब क्रिएटर समिट",
    "event.37.description": "सफल यूट्यूबर्स से मुद्रीकरण रणनीतियां और विकास हैक्स सीखें।",
    "event.3.title": "कथक नृत्य ऑनलाइन सीखें",
    "event.3.description": "इस व्यापक ऑनलाइन कार्यशाला में कथक नृत्य की मूल बातों में माहिर बनें। व्यक्तिगत फीडबैक के साथ कथक मास्टरो से सीखें।",
    "event.10.title": "डिजिटल आर्ट एंड एनिमेशन एक्सपो",
    "event.10.description": "उभरते डिजिटल कलाकारों से डिजिटल कलाकृतियों, एनिमेशन और इंटरैक्टिव स्थापनाओं का प्रदर्शन। तकनीक और कला पेशेवरों के साथ नेटवर्किंग।",
    "event.17.title": "पारंपरिक जात्रा लोक रंगमंच",
    "event.17.description": "पौराणिक कथाओं और सामाजिक विषयों की विशेषता वाले पारंपरिक जात्रा प्रदर्शन के साथ प्रामाणिक बंगाली लोक रंगमंच का अनुभव करें।",
    "event.27.title": "सोशल मीडिया इन्फ्लुएंसर समिट",
    "event.27.description": "शीर्ष प्रभावकों से जुड़ें और अपनी सोशल मीडिया उपस्थिति बढ़ाने की रणनीतियां सीखें।",
    "event.44.title": "साहित्यिक महोत्सव 2025",
    "event.44.description": "पैनल चर्चा, पुस्तक पठन और लेखक बातचीत के साथ साहित्य का जश्न मनाएं।",
    "event.4.title": "इंडी सिनेमा शोकेस 2025",
    "event.4.description": "भारत और दुनिया भर के उभरते फिल्म निर्माताओं की स्वतंत्र फिल्मों की खोज करें। निर्देशकों के साथ प्रश्नोत्तर सत्र।",
    "event.36.title": "यूट्यूबर मीटअप 2025",
    "event.36.description": "लोकप्रिय यूट्यूबर्स से मिलें और सामग्री निर्माण और वीडियो उत्पादन के बारे में जानें।",
    "event.56.title": "फ्यूजन म्यूजिक नाइट",
    "event.56.description": "प्रतिभाशाली वाद्ययंत्र वादकों द्वारा पारंपरिक और आधुनिक संगीत के मिश्रण का अनुभव करें।",
    "event.59.title": "अंतर्राष्ट्रीय जादू महोत्सव",
    "event.59.description": "विश्व स्तरीय जादूगरों को अविश्वसनीय भ्रम और जादू के करतब दिखाते हुए देखें।",
    "event.16.title": "लाइव संगीत के साथ कथक नृत्य प्रदर्शन",
    "event.16.description": "लाइव शास्त्रीय संगीत के साथ कथक नृत्य की सुंदरता का अनुभव करें। मास्टर नर्तक तबला और सितार संगत के साथ पारंपरिक नृत्यकला प्रस्तुत करते हैं।",
    "event.28.title": "इन्फ्लुएंसर मीट एंड ग्रीट",
    "event.28.description": "अपने पसंदीदा सोशल मीडिया इन्फ्लुएंसर्स से व्यक्तिगत रूप से मिलें और विशेष सामग्री प्राप्त करें।",
    "event.52.title": "स्ट्रीट थिएटर फेस्टिवल",
    "event.52.description": "सामाजिक मुद्दों को संबोधित करने वाले आकर्षक स्ट्रीट थिएटर प्रदर्शन देखें।",
    "event.49.title": "इंडियन आइडल स्टार्स के साथ मीट एंड ग्रीट",
    "event.49.description": "अपने पसंदीदा इंडियन आइडल प्रतियोगियों के साथ विशेष मीट एंड ग्रीट सत्र।",
    "event.40.title": "हिप हॉप डांस बैटल",
    "event.40.description": "इस उच्च ऊर्जा नृत्य प्रतियोगिता में सर्वश्रेष्ठ हिप हॉप नर्तकों को प्रतिस्पर्धा करते देखें।",
    "event.54.title": "शास्त्रीय वाद्य संगीत कॉन्सर्ट",
    "event.54.description": "शास्त्रीय संगीत बजाने वाले मास्टर वाद्ययंत्र वादकों के मंत्रमुग्ध कर देने वाले प्रदर्शन का आनंद लें।",
    "event.11.title": "पारंपरिक कठपुतली रंगमंच शो - कठपुतली",
    "event.11.description": "पारंपरिक भारतीय लोककथाओं और पौराणिक कथाओं को दर्शाने वाले लाइव प्रदर्शन के साथ कठपुतली रंगमंच की प्राचीन कला का अनुभव करें।",
    "event.19.title": "डॉक्यूमेंट्री फिल्म फेस्टिवल",
    "event.19.description": "दुनिया भर से पुरस्कार विजेता डॉक्यूमेंट्री का एक क्यूरेटेड चयन, जिसमें संस्कृति, समाज और मानवीय अनुभवों की कहानियां हैं।",
    "event.20.title": "अंतर्राष्ट्रीय लघु फिल्म शोकेस",
    "event.20.description": "अंतर्राष्ट्रीय फिल्म निर्माताओं की पुरस्कार विजेता लघु फिल्मों का संग्रह, जो विविध कहानी कहने और नवीन छायांकन को प्रदर्शित करता है।",
    "event.25.title": "जॉलीवुड स्टार नाइट",
    "event.25.description": "इस विशेष फैन मीट और मनोरंजन रात में अपने पसंदीदा जॉलीवुड सितारों से मिलें।",
    "event.57.title": "जादू शो एक्सट्रावैगेंजा",
    "event.57.description": "पेशेवर जादूगरों द्वारा मन को चकित कर देने वाले जादू के करतब और भ्रम से हैरान हो जाएं।",
    "event.39.title": "समकालीन नृत्य प्रदर्शन",
    "event.39.description": "पेशेवर नर्तकों द्वारा शानदार समकालीन नृत्य प्रदर्शन का अनुभव करें।",
    "event.62.title": "लाइव रेडियो शो रिकॉर्डिंग",
    "event.62.description": "लोकप्रिय आरजे और सेलिब्रिटी मेहमानों के साथ लाइव रेडियो शो रिकॉर्डिंग का हिस्सा बनें।",
    "event.9.title": "शुरुआती लोगों के लिए भरतनाट्यम नृत्य कार्यशाला",
    "event.9.description": "अनुभवी प्रशिक्षकों से शास्त्रीय दक्षिण भारतीय नृत्य रूप भरतनाट्यम सीखें। बिना किसी पूर्व अनुभव वाले शुरुआती लोगों के लिए एकदम सही।",
    "event.21.title": "ओलीवुड फिल्म प्रीमियर नाइट",
    "event.21.description": "स्टार कास्ट मीट एंड ग्रीट के साथ नवीनतम ओड़िया ब्लॉकबस्टर फिल्म का विशेष प्रीमियर।",
    "event.30.title": "स्टैंड-अप कॉमेडी नाइट",
    "event.30.description": "शीर्ष कॉमेडियनों के साथ उनके सर्वश्रेष्ठ स्टैंड-अप रूटीन का प्रदर्शन करते हुए जोर से हंसें।",
    "event.51.title": "थिएटर प्ले - आधुनिक नाटक",
    "event.51.description": "इस समकालीन रंगमंच प्रस्तुति के माध्यम से शक्तिशाली कहानी कहने का अनुभव करें।",
    "event.24.title": "जॉलीवुड फिल्म फेस्टिवल",
    "event.24.description": "पुरस्कार विजेता जॉलीवुड फिल्मों की स्क्रीनिंग के साथ झारखंड सिनेमा का जश्न मनाएं।",
    "event.42.title": "पुस्तक लॉन्च और लेखक मुलाकात",
    "event.42.description": "इस विशेष पुस्तक लॉन्च कार्यक्रम में बेस्टसेलिंग लेखकों से मिलें और अपनी पुस्तकों पर हस्ताक्षर प्राप्त करें।",
    "event.13.title": "स्ट्रीट आर्ट एंड ग्रैफिटी कार्यशाला",
    "event.13.description": "पेशेवर स्ट्रीट आर्टिस्टों से शहरी कला और ग्रैफिटी तकनीक सीखें। उचित मार्गदर्शन और सुरक्षा के साथ अपना खुद का भित्तिचित्र बनाएं।",
    "event.29.title": "कंटेंट क्रिएटर कार्यशाला",
    "event.29.description": "सफल इन्फ्लुएंसर्स और क्रिएटर्स से कंटेंट क्रिएशन टिप्स और ट्रिक्स सीखें।",
    "event.60.title": "आरजे मीट एंड ग्रीट",
    "event.60.description": "अपने पसंदीदा रेडियो जॉकी से मिलें और रेडियो ब्रॉडकास्टिंग की दुनिया के बारे में जानें।",
    "event.38.title": "यूट्यूबर्स द्वारा वीडियो एडिटिंग कार्यशाला",
    "event.38.description": "पेशेवर यूट्यूबर्स से वीडियो एडिटिंग तकनीकों में माहिर बनें।",
    "event.58.title": "बच्चों के लिए जादू कार्यशाला",
    "event.58.description": "बच्चों के लिए डिज़ाइन की गई इस मजेदार कार्यशाला में सरल जादू के करतब सीखें।",
    "event.45.title": "कविता स्लैम प्रतियोगिता",
    "event.45.description": "लाइव प्रदर्शन के साथ इस रोमांचक कविता स्लैम में कवियों को प्रतिस्पर्धा करते देखें।",
    "event.5.title": "बॉलीवुड कलाकारों से कस्टम व्यक्तिगत गीत",
    "event.5.description": "पेशेवर बॉलीवुड गायकों से एक व्यक्तिगत गीत, जन्मदिन की शुभकामना, या विशेष संदेश का आदेश दें। जश्न के लिए एकदम सही!",
    "event.43.title": "लेखक कार्यशाला",
    "event.43.description": "पुरस्कार विजेता लेखकों से रचनात्मक लेखन तकनीक सीखें।",
    "event.50.title": "इंडियन आइडल गायन कार्यशाला",
    "event.50.description": "इस इंटरैक्टिव कार्यशाला में इंडियन आइडल प्रतियोगियों से गायन तकनीक सीखें।",
    "event.32.title": "ओपन माइक कॉमेडी नाइट",
    "event.32.description": "स्टैंड-अप कॉमेडी आजमाएं या उभरते कॉमेडियनों को प्रदर्शन करते देखें।",
    "event.46.title": "ओपन माइक कविता रात",
    "event.46.description": "इस ओपन माइक कविता सत्र में अपनी कविता साझा करें या सुंदर पंक्तियां सुनें।",
    "event.61.title": "रेडियो जॉकी कार्यशाला",
    "event.61.description": "पेशेवर आरजे से आवाज मॉड्यूलेशन, एंकरिंग और ब्रॉडकास्टिंग कौशल सीखें।",
    "event.53.title": "रंगमंच कलाकारों द्वारा अभिनय कार्यशाला",
    "event.53.description": "इस हाथों-हाथ कार्यशाला में अनुभवी रंगमंच कलाकारों से अभिनय कौशल सीखें।",
    "event.41.title": "शुरुआती लोगों के लिए नृत्य कार्यशाला",
    "event.41.description": "इस शुरुआती-अनुकूल कार्यशाला में पेशेवर नर्तकों से विभिन्न नृत्य शैलियां सीखें।",
    "event.55.title": "पेशेवर संगीतकारों द्वारा गिटार कार्यशाला",
    "event.55.description": "पेशेवर वाद्ययंत्र वादकों से गिटार तकनीक सीखें।",
    "event.23.title": "ओलीवुड अभिनेता कार्यशाला",
    "event.23.description": "इस गहन कार्यशाला में प्रसिद्ध ओलीवुड अभिनेताओं से अभिनय तकनीक सीखें।",
    "event.26.title": "जॉलीवुड फिल्ममेकिंग कार्यशाला",
    "event.26.description": "अनुभवी जॉलीवुड निर्देशकों और सिनेमैटोग्राफरों से फिल्म निर्माण की कला सीखें।",
    "event.47.title": "प्रसिद्ध कवियों के साथ कविता कार्यशाला",
    "event.47.description": "प्रसिद्ध कवियों से कविता लेखन की कला सीखें।",
    "event.6.title": "होली महोत्सव - संगीत और नृत्य उत्सव",
    "event.6.description": "लाइव संगीत प्रदर्शन, पारंपरिक नृत्यों और सांस्कृतिक उत्सवों के साथ रंगों के त्योहार का जश्न मनाएं।",
    "organizer.Odissi Classical Arts": "ओडिसी शास्त्रीय कला",
    "organizer.Global Jatra Collective": "ग्लोबल जात्रा समूह",
    "organizer.MOOKALAA Artists Network": "MOOKALAA कलाकार नेटवर्क",
    "organizer.Dance India Movement": "डांस इंडिया मूवमेंट",
    "location.Bhubaneswar": "भुवनेश्वर",
    "location.Kolkata": "कोलकाता",
    "location.Virtual": "वर्चुअल",
    "location.Bangalore": "बैंगलोर",
    "location.Delhi": "दिल्ली",
    "location.Mumbai": "मुंबई",
    "location.New York": "न्यूयॉर्क",
    "location.Chennai": "चेन्नई",
    "location.Hyderabad": "हैदराबाद",
    "location.Jaipur": "जयपुर",
    "location.Pune": "पुणे",
    "location.Ahmedabad": "अहमदाबाद",
    "location.Odisha": "ओडिशा",
    "location.Cuttack": "कटक",
    "location.Ranchi": "रांची",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  const translateCategory = (category: string): string => {
    return t(`categories.${category}`)
  }

  const translateEvent = (eventId: string, field: 'title' | 'description', defaultValue: string): string => {
    const key = `event.${eventId}.${field}`
    const translated = translations[language][key as keyof typeof translations.en]
    return translated || defaultValue
  }

  const translateOrganizer = (organizerName: string): string => {
    const key = `organizer.${organizerName}`
    const translated = translations[language][key as keyof typeof translations.en]
    return translated || organizerName
  }

  const translateLocation = (location: string): string => {
    if (language === 'en') return location
    
    // Translation map for location parts
    const locationMap: { [key: string]: string } = {
      'Bhubaneswar': 'भुवनेश्वर',
      'Kolkata': 'कोलकाता',
      'Virtual': 'वर्चुअल',
      'Bangalore': 'बैंगलोर',
      'Delhi': 'दिल्ली',
      'Mumbai': 'मुंबई',
      'New York': 'न्यूयॉर्क',
      'Chennai': 'चेन्नई',
      'Hyderabad': 'हैदराबाद',
      'Jaipur': 'जयपुर',
      'Pune': 'पुणे',
      'Ahmedabad': 'अहमदाबाद',
      'Odisha': 'ओडिशा',
      'Cuttack': 'कटक',
      'Ranchi': 'रांची',
      'West Bengal': 'पश्चिम बंगाल',
      'Karnataka': 'कर्नाटक',
      'India': 'भारत',
      'Maharashtra': 'महाराष्ट्र',
      'Tamil Nadu': 'तमिलनाडु',
      'Telangana': 'तेलंगाना',
      'Rajasthan': 'राजस्थान',
      'Gujarat': 'गुजरात',
      'Jharkhand': 'झारखंड',
      'USA': 'यूएसए',
      'Online': 'ऑनलाइन',
      'Odissi': 'ओडिसी'
    }
    
    // Replace each part of the location
    let translatedLocation = location
    Object.keys(locationMap).forEach(key => {
      const regex = new RegExp(key, 'g')
      translatedLocation = translatedLocation.replace(regex, locationMap[key])
    })
    
    return translatedLocation
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, translateCategory, translateEvent, translateOrganizer, translateLocation }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}
